glossary_terms <- data.frame(
  id = c(
    "alternative-hypothesis", "anova", "categorical-data", "confidence-interval",
    "continuous-data", "correlation", "degrees-of-freedom", "dependent-variable",
    "effect-size", "homogeneity-of-variance", "hypothesis-testing", "independent-variable",
    "interval-data", "likert-scale", "mean", "median",
    "non-parametric-test", "normal-distribution", "null-hypothesis", "ordinal-data",
    "outlier", "p-value", "paired-data", "parametric-test",
    "post-hoc-test", "power", "ratio-data", "regression",
    "sample-size", "significance-level", "skewness", "sphericity",
    "standard-deviation", "statistical-significance", "type-i-error", "type-ii-error",
    "variance"
  ),
  term = c(
    "Alternative Hypothesis", "ANOVA", "Categorical Data", "Confidence Interval",
    "Continuous Data", "Correlation", "Degrees of Freedom", "Dependent Variable",
    "Effect Size", "Homogeneity of Variance", "Hypothesis Testing", "Independent Variable",
    "Interval Data", "Likert Scale", "Mean", "Median",
    "Non-Parametric Test", "Normal Distribution", "Null Hypothesis", "Ordinal Data",
    "Outlier", "P-Value", "Paired Data", "Parametric Test",
    "Post-Hoc Test", "Power", "Ratio Data", "Regression",
    "Sample Size", "Significance Level", "Skewness", "Sphericity",
    "Standard Deviation", "Statistical Significance", "Type I Error", "Type II Error",
    "Variance"
  ),
  definition = c(
    "The hypothesis that there IS a real effect, difference, or relationship in the population. It is what you are trying to find evidence for, often written as H₁ or Hₐ. A small p-value provides evidence in favor of the alternative hypothesis.",
    "Analysis of Variance — a statistical test used to compare the means of three or more groups simultaneously. ANOVA tests whether at least one group mean differs from the others, but does not tell you which groups differ (that requires a post-hoc test).",
    "Data that falls into distinct, named groups or categories with no meaningful numerical order. Examples include species (dog/cat/bird), blood type (A/B/AB/O), and survey responses (yes/no/maybe). You cannot calculate a meaningful average of categorical data.",
    "A range of values computed from your sample that is likely to contain the true population parameter. A 95% confidence interval means if you repeated the study many times, 95% of the calculated intervals would contain the true value. Wider intervals indicate more uncertainty.",
    "Numerical data that can take any value within a range, including decimals. Examples include height (1.73 m), reaction time (342.5 ms), and temperature (98.6°F). Continuous data is always numerical.",
    "A measure of the direction and strength of the linear relationship between two numerical variables. Ranges from −1 (perfect negative relationship) to +1 (perfect positive relationship), with 0 indicating no linear relationship. Correlation does not imply causation.",
    "The number of values in a statistical calculation that are free to vary. In practice it is closely related to sample size — larger samples give more degrees of freedom, which generally makes tests more reliable and powerful.",
    "The variable you are measuring or trying to predict — the outcome. Also called the response variable. Example: if studying the effect of fertilizer on plant height, plant height is the dependent variable. In a regression equation it is usually labeled Y.",
    "A standardized measure of how large or practically meaningful a difference or relationship is, separate from whether it is statistically significant. Common measures include Cohen’s d (for group differences) and r (for correlations). A result can be statistically significant but have a tiny effect size.",
    "An assumption that the groups being compared have similar variances (spread) in their data. Also called homoscedasticity. When violated — one group’s data is far more spread out than another’s — tests like ANOVA become unreliable. Levene’s test checks this assumption.",
    "A formal procedure for using sample data to evaluate a claim about a population. Steps include: state null and alternative hypotheses, collect data, compute a test statistic, calculate a p-value, and decide whether to reject the null hypothesis based on a pre-set significance level.",
    "The variable you manipulate or use to predict another variable. Also called the predictor or explanatory variable. Example: in a drug trial, the dosage is the independent variable. In a regression equation it is usually labeled X.",
    "Numerical data with equal, meaningful spacing between values, but no true zero point (zero does not mean the complete absence of the quantity). Examples: temperature in Celsius (0°C is not “no temperature”) and IQ scores. Meaningful differences can be calculated, but not ratios.",
    "A rating scale commonly ranging from 1–5 or 1–7, anchored by labels like “Strongly Disagree” to “Strongly Agree.” Technically ordinal data, though many researchers treat 5- or 7-point Likert items as continuous in practice. The appropriate analysis depends on your assumptions and sample size.",
    "The arithmetic average of a dataset: the sum of all values divided by the count. The mean is sensitive to outliers — a single very large or small value can pull it away from the center of most of the data.",
    "The middle value of a dataset when all values are sorted in order. Half the values fall above the median and half below it. Less sensitive to outliers than the mean, making it a better measure of center for skewed distributions.",
    "A statistical test that does not assume the data follows a specific distribution like the normal distribution. Non-parametric tests typically rank the data and analyze those ranks. They are appropriate for ordinal data, small samples, and situations where normality assumptions are violated.",
    "A symmetric, bell-shaped distribution where most values cluster near the mean and fewer values appear in the tails. Many parametric tests assume data is normally distributed. You can assess normality with histograms, Q-Q plots, or formal tests like Shapiro-Wilk.",
    "The hypothesis of no effect, no difference, and no relationship — written as H₀. Statistical tests try to find evidence against it. Failing to reject H₀ does not prove it is true; it only means your data did not provide enough evidence to reject it.",
    "Data that has a meaningful order but unknown or unequal spacing between categories. Examples include rankings (1st, 2nd, 3rd), satisfaction levels (poor/fair/good/excellent), and pain ratings (0–10). You can say one value is greater than another, but not by how much.",
    "An observation that falls far from the rest of the data. Outliers can distort means, inflate variances, and violate normality assumptions. They should always be investigated — they may represent data entry errors, measurement mistakes, or genuinely unusual cases.",
    "The probability of observing a result at least as extreme as yours, assuming the null hypothesis is true. A small p-value (typically < 0.05) is evidence against the null hypothesis. The p-value is NOT the probability that the null hypothesis is true, and NOT the probability your result occurred by chance.",
    "Data where observations come in matched pairs — for example, measuring the same person before and after a treatment, or pairing subjects by a matching variable. Paired data violates the independence assumption of tests like the independent t-test; paired tests must be used instead.",
    "A statistical test that assumes the data follows a specific distribution, usually the normal distribution. Parametric tests (t-tests, ANOVA, Pearson correlation) are generally more powerful than non-parametric tests when assumptions are met, meaning they are better at detecting real effects.",
    "A follow-up test performed after a significant ANOVA result to identify which specific group pairs differ from each other. Common options include Tukey’s HSD, Bonferroni correction, and Dunn’s test (for Kruskal-Wallis). Post-hoc tests control the Type I error rate when making multiple comparisons.",
    "The probability that a statistical test will correctly detect a real effect (i.e., reject a false null hypothesis). Power = 1 − β. Increasing sample size, effect size, or the significance level all increase power. A power of 0.80 (80%) is commonly considered adequate.",
    "Numerical data with equal spacing between values AND a true zero point, meaning zero represents the complete absence of the quantity. Examples: height, weight, income, and reaction time. Ratio data allows meaningful ratio statements (“twice as fast”, “half as heavy”).",
    "A statistical method for modeling the relationship between a dependent (outcome) variable and one or more predictor (independent) variables. Regression can be used to predict outcomes and understand which predictors have the strongest relationship with the outcome.",
    "The number of observations in your study (n). Larger sample sizes reduce sampling error, increase statistical power, and make tests more robust to violations of assumptions. Many statistical tests have minimum sample size requirements.",
    "The threshold p-value (called α, alpha) used to decide whether to reject the null hypothesis. The most common choice is α = 0.05 (5%). A lower threshold (e.g., 0.01) makes it harder to reject H₀ and reduces Type I error, but also reduces power.",
    "A measure of the asymmetry of a distribution. Positive skew means a long tail to the right (a few very large values); negative skew means a long tail to the left. Strongly skewed data may violate normality assumptions for parametric tests.",
    "An assumption required for repeated measures ANOVA stating that the variances of the differences between all pairs of time points (or conditions) are equal. Mauchly’s test checks this. If violated, apply a correction such as Greenhouse–Geisser or Hüynh–Feldt.",
    "A measure of the spread or variability in a dataset, expressed in the same units as the data. It equals the square root of the variance. In a normal distribution, approximately 68% of values fall within one standard deviation of the mean.",
    "A result is statistically significant when its p-value falls below the chosen significance level (α). It means the result is unlikely to have occurred by chance alone under the null hypothesis. Statistical significance does not equal practical importance — always consider effect size too.",
    "Incorrectly rejecting the null hypothesis when it is actually true — a false positive. The probability of a Type I error equals the significance level (α). Example: concluding a new drug is effective when it actually has no effect.",
    "Failing to reject the null hypothesis when it is actually false — a false negative. Denoted β. The probability of avoiding Type II error is statistical power (1 − β). Example: concluding a treatment has no effect when it actually does. Increasing sample size reduces Type II error.",
    "A measure of how spread out the values in a dataset are around the mean. Calculated as the average squared deviation from the mean. Standard deviation is its square root and is easier to interpret because it is in the original units. High variance means data points are widely scattered."
  ),
  stringsAsFactors = FALSE
)
